name: flutter_application_2
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  http: ^0.13.3
  path_provider: ^2.0.11
  image_picker: ^0.8.4+8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data.json
    - assets/Homepage.jpg
    - assets/loves.jpg
    - assets/Pink.jpg
    - assets/images/
    - assets/noimg.jpg
